import type { ForumCategory, ForumThread } from '@/types/content'

// ── Forum categories ──────────────────────────────────────────
export function getForumCategories(): ForumCategory[] {
  return [
    {
      id: 'kiralama',
      colorClass: 'blue',
      title: 'Tekne Kiralama',
      description: 'Kiralama süreci, fiyatlar, en iyi tekneler ve dikkat edilmesi gerekenler hakkında her şey.',
      threadCount: 312,
      postCount: 2841,
      lastThread: {
        title: 'Bodrum\'da günlük kiralama fiyatları nasıl?',
        author: 'denizci_ali',
        date: '2 saat önce',
      },
    },
    {
      id: 'rotalar',
      colorClass: 'coral',
      title: 'Rotalar & Gizli Koylar',
      description: 'Ege ve Akdeniz\'in unutulmaz rotaları, sır gibi saklanan koylar ve liman tavsiyeleri.',
      threadCount: 487,
      postCount: 5120,
      lastThread: {
        title: 'Kaş\'tan Göcek\'e 7 günlük rota önerisi',
        author: 'yelken_ozgur',
        date: '15 dk önce',
      },
    },
    {
      id: 'deneyimler',
      colorClass: 'green',
      title: 'Deneyimler & Aktiviteler',
      description: 'Dalış, yoga, balıkçılık, mutfak turları ve diğer deniz deneyimlerine ait paylaşımlar.',
      threadCount: 198,
      postCount: 1647,
      lastThread: {
        title: 'Marmaris\'te dalış kursu — hangi okulu seçmeli?',
        author: 'zeynep_dalgic',
        date: '1 saat önce',
      },
    },
    {
      id: 'kaptan',
      colorClass: 'purple',
      title: 'Kaptan & Mürettebat',
      description: 'Kaptan seçimi, mürettebat deneyimleri ve profesyonel denizcilik tavsiyeleri.',
      threadCount: 134,
      postCount: 890,
      lastThread: {
        title: 'İyi kaptan nasıl anlaşılır? 10 ipucu',
        author: 'kaptan_mehmet',
        date: '3 saat önce',
      },
    },
    {
      id: 'bakim',
      colorClass: 'orange',
      title: 'Tekne Bakımı & Teknik',
      description: 'Tekne sahipleri için bakım, onarım, donanım ve teknik konular.',
      threadCount: 89,
      postCount: 634,
      lastThread: {
        title: 'Yelkenli motor bakımı için Bodrum\'da usta tavsiyesi',
        author: 'tekne_sahibi',
        date: '5 saat önce',
      },
    },
    {
      id: 'genel',
      colorClass: 'teal',
      title: 'Genel Sohbet',
      description: 'Denizle ilgili her konu — hava durumu, sohbet, tanışma ve duyurular.',
      threadCount: 521,
      postCount: 4380,
      lastThread: {
        title: 'Bu hafta sonu hava durumu nasıl? Çıkacak mısınız?',
        author: 'deniz_sevdalisi',
        date: '8 dk önce',
      },
    },
  ]
}

// ── Forum threads (latest & hot) ──────────────────────────────
export function getForumThreads(): ForumThread[] {
  return [
    {
      id: 'th1',
      categoryId: 'rotalar',
      categoryLabel: 'Rotalar & Gizli Koylar',
      categoryColor: 'coral',
      title: 'Kaş\'tan Göcek\'e 7 günlük mavi yolculuk — tam gezi notları + foto',
      excerpt: 'Geçen ay eşimle çıktığımız bu rotayı sizlerle paylaşmak istedim. Her gün hangi koyda demir attık, ne yedik, ne içtik, tüm detaylar burada.',
      author: {
        name: 'Özgür Y.',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=80&q=80',
        postCount: 247,
        joinYear: 2022,
        badge: 'Deniz Kurdu',
        location: 'İstanbul',
      },
      createdAt: '15 dk önce',
      replyCount: 23,
      viewCount: 1840,
      likeCount: 67,
      isPinned: false,
      isHot: true,
      tags: ['Kaş', 'Göcek', 'Mavi Yolculuk', 'Rota'],
      lastReply: {
        author: 'Mert A.',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=80&q=80',
        date: '3 dk önce',
      },
    },
    {
      id: 'th2',
      categoryId: 'kiralama',
      categoryLabel: 'Tekne Kiralama',
      categoryColor: 'blue',
      title: 'Bodrum\'da Ağustos ayı kiralama fiyatları 2026 — güncel fiyat tablosu',
      excerpt: 'Birçok firmayla görüştüm ve fiyatları karşılaştırdım. Yelkenliden gulet\'e kadar güncel rakamları paylaşıyorum.',
      author: {
        name: 'Ayşe K.',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=80&q=80',
        postCount: 89,
        joinYear: 2023,
        badge: null,
        location: 'Ankara',
      },
      createdAt: '1 saat önce',
      replyCount: 41,
      viewCount: 3210,
      likeCount: 112,
      isPinned: true,
      isHot: true,
      tags: ['Bodrum', 'Fiyat', 'Kiralama', '2026'],
      lastReply: {
        author: 'Zeynep M.',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=80&q=80',
        date: '12 dk önce',
      },
    },
    {
      id: 'th3',
      categoryId: 'deneyimler',
      categoryLabel: 'Deneyimler & Aktiviteler',
      categoryColor: 'green',
      title: 'Teknede yoga workshop deneyimim — SeaHub üzerinden aldım',
      excerpt: 'İlk başta biraz şüpheliydim ama inanılmaz bir deneyimdi. Sabah güneş doğarken Ege\'de yoga yapmak... Kelimelerle anlatılmaz.',
      author: {
        name: 'Selin D.',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=80&q=80',
        postCount: 34,
        joinYear: 2024,
        badge: null,
        location: 'İzmir',
      },
      createdAt: '3 saat önce',
      replyCount: 18,
      viewCount: 945,
      likeCount: 88,
      isPinned: false,
      isHot: false,
      tags: ['Yoga', 'Workshop', 'Deneyim'],
      lastReply: {
        author: 'Can T.',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=80&q=80',
        date: '45 dk önce',
      },
    },
    {
      id: 'th4',
      categoryId: 'rotalar',
      categoryLabel: 'Rotalar & Gizli Koylar',
      categoryColor: 'coral',
      title: 'Çeşme\'de kimsenin bilmediği 5 koy — GPS koordinatlarıyla',
      excerpt: 'Bodrum ve Marmaris\'e gitmeye gerek yok. Çeşme\'de de muhteşem, ıssız koylar var. Koordinatları ve nasıl gidileceğini paylaşıyorum.',
      author: {
        name: 'Burak A.',
        avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=80&q=80',
        postCount: 156,
        joinYear: 2021,
        badge: 'Koy Avcısı',
        location: 'İzmir',
      },
      createdAt: '6 saat önce',
      replyCount: 37,
      viewCount: 2780,
      likeCount: 143,
      isPinned: false,
      isHot: true,
      tags: ['Çeşme', 'Gizli Koy', 'GPS'],
      lastReply: {
        author: 'Hasan K.',
        avatar: 'https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&w=80&q=80',
        date: '1 saat önce',
      },
    },
    {
      id: 'th5',
      categoryId: 'kaptan',
      categoryLabel: 'Kaptan & Mürettebat',
      categoryColor: 'purple',
      title: 'Kaptan seçerken bunlara dikkat edin — 10 yıllık tecrübemden tavsiyeler',
      excerpt: 'Hem tekne sahibi hem misafir olarak binlerce saatlik deneyimim var. İyi kaptanı kötüden ayıran özellikleri anlattım.',
      author: {
        name: 'Kaptan Mehmet',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=80&q=80',
        postCount: 412,
        joinYear: 2020,
        badge: 'Doğrulanmış Kaptan',
        location: 'Bodrum',
      },
      createdAt: '1 gün önce',
      replyCount: 56,
      viewCount: 4120,
      likeCount: 198,
      isPinned: true,
      isHot: false,
      tags: ['Kaptan', 'Tavsiye', 'Güvenlik'],
      lastReply: {
        author: 'Tarık Y.',
        avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=80&q=80',
        date: '4 saat önce',
      },
    },
    {
      id: 'th6',
      categoryId: 'genel',
      categoryLabel: 'Genel Sohbet',
      categoryColor: 'teal',
      title: 'Bu hafta sonu Ege\'de hava durumu — çıkmaya değer mi?',
      excerpt: 'Meteoroloji 3-4 poyraz bekliyor Çanakkale bölgesinde. Güneydeyseniz daha sakin. Deneyimlerini paylaşanlar var mı?',
      author: {
        name: 'Rüzgar Takipçisi',
        avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=80&q=80',
        postCount: 22,
        joinYear: 2025,
        badge: null,
        location: 'İstanbul',
      },
      createdAt: '8 dk önce',
      replyCount: 9,
      viewCount: 312,
      likeCount: 14,
      isPinned: false,
      isHot: false,
      tags: ['Hava Durumu', 'Hafta Sonu'],
      lastReply: {
        author: 'Deniz E.',
        avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=80&q=80',
        date: '5 dk önce',
      },
    },
    {
      id: 'th7',
      categoryId: 'bakim',
      categoryLabel: 'Tekne Bakımı & Teknik',
      categoryColor: 'orange',
      title: 'Yelkenli bakımı için Bodrum\'da en iyi tersane hangisi?',
      excerpt: 'İlkbahar bakımı zamanı geldi. Farklı yerleri deneyimleyenler görüşlerini paylaşabilir mi? Fiyat/performans açısından değerlendirme bekliyorum.',
      author: {
        name: 'Tekne Sahibi C.',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=80&q=80',
        postCount: 67,
        joinYear: 2022,
        badge: null,
        location: 'Bodrum',
      },
      createdAt: '5 saat önce',
      replyCount: 12,
      viewCount: 680,
      likeCount: 31,
      isPinned: false,
      isHot: false,
      tags: ['Bakım', 'Tersane', 'Bodrum'],
      lastReply: {
        author: 'Ali M.',
        avatar: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&w=80&q=80',
        date: '2 saat önce',
      },
    },
  ]
}
